version: "3.7"
services:
  node_website:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/node/app
      #      restart: always
    container_name: website
    ports:
#      - "8200:8200"
      - "8080:8080"
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=development
      #- NODE_ENV=production
    stdin_open: true
    command: /bin/bash -c  "npm run serve"
